- Servers & Clients = End Hosts & Endpoints
- Host based Firewalls = firewalls are software applications that filter traffic entering and exiting a host machine, like a PC.are software applications that filter traffic entering and exiting a host machine, like a PC.
- A Switch = has many network interfaces for end hosts to connect to.
- A Switch = Provides connectivity to hosts within the same LAN (Local Area Network)
- A Switch = Cisco “Catalyst” 
- A Client = is a device that accesses a service made available by a server.
- A Server = A device that provides functions or services for clients
- A Router = Is used to send data over the internet
- A Router = Cisco ISR
- Routers have Fewer network interfaces than switches
- A Firewall = Cisco ASA
- A Firewall = Cisco Firepower
- A Firewall = Monitors and controls network traffic based on configured Rules
- A Next-Generation Firewall = A firewall which combines a traditional firewall with more advanced filtering functionalities is known as a Next-Generation firewall. 
- A computer network is as digital telecommunications network which allows NODES to share resources
- Y/N: Can a single device be both a client and a server? - Yes
